print('Hello world')
print('       1')
print('     2 3')
print('   4 5 6')
print('7 8 9 10')
print('Y   Y M   M')
print(' Y Y  MM MM')
print('  Y   MM MM')
print('  Y   M M M')
print('  Y   M   M')
print('  Y   M   M')